### ISSUE TITLE
Suggestion: Pull CP names and spawn path names

### ISSUE THREAD

**Issue by SpencerJones00** [marth8880/ZeroWorldStats#4]
Not sure if this is possible, but as someone who's trying to set up AI Hero Support without a working zero editor it would be a nice touch. Your scripts for MEU were very helpful for conquest but are missing CTF game modes. - Nate

**Comment by marth8880** [comment]
Shouldn't be terribly difficult to build a simple parser that extracts the name from the Object line in WLD/LYR files.

**Comment by marth8880** [comment]
Update: It works! 

![image](https://user-images.githubusercontent.com/12036256/43988596-0dd72314-9cee-11e8-94e2-894bd69453eb.png)

**Comment by marth8880** [comment]
Task complete in 32b36f7 - closing.

![image](https://user-images.githubusercontent.com/12036256/43988901-4db7b9ac-9cf4-11e8-8d5d-3a6c0c5b8ac4.png)
